labelToAdd: 'need more info'
labelsToCheck:
  - bug
commentHeader: 'More information is required to proceed with this issue. Please comment with items below, or the issue will be closed in a week.'
requiredItems:
  -
    response: '- The information requested in the bug issue template'
    requireAll: true
    content:
      - '## Actual Behavior'
      - '## Expected Behavior'
  -
    response: '- A sample that reproduces the issue'
    requireAll: false
    content:
      - jsbin.com
      - codepen.io
      - jsfiddle.net
      - codesandbox.io