labelToAdd: 'need more info'
labelsToCheck:
  - bug
commentHeader: 'This is being marked as need info for the following reasons:'
commentFooter: 'Please comment with items above, or the issue will be closed in a week'
requiredItems:
  -
    response: '&nbsp;- Use the issue template for bugs'
    requireAll: true
    content:
      - '## Actual Behavior'
      - '## Expected Behavior'
  -
    response: '&nbsp;- Include a sample that reproduces the issue'
    requireAll: false
    content:
      - jsbin.com
      - codepen.io
      - jsfiddle.net
      - codesandbox.io