labelToAdd: 'need more info'
labelsToCheck:
  - bug
  - enhancement
requiredItems:
  -
    response: '- Use the appropriate format from the issue templates'
    requireAll: true
    content:
      - '## Actual Behavior'
      - '## Expected Behavior'
  -
    response: '- A sample that reproduces the issue'
    requireAll: false
    content:
      - jsbin.com
      - codepen.io
      - jsfiddle.net
      - codesandbox.io
# optional properties below
commentHeader: 'More information is required to proceed:'
commentFooter: 'This issue will be automatically closed in a week if the information is not provided. Thanks for your understanding.'
caseSensitive: true
exemptUsers:
  - maintainer-username1
  - maintainer-username2
