name: 'Need More Info'
description: 'Requests more info when required content is not included in an issue'
author: 'Ben Elan'
inputs:
  repo-token:
    description: 'Token for the repository. Defaults to {{ secrets.GITHUB_TOKEN }}.'
    default: {{ secrets.GITHUB_TOKEN }}
    required: false
  config-path:
    description: 'Path to the config file. Defaults to .github/need-info.yml.'
    default: '.github/need-info.yml'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'info'
  color: 'yellow'
