name: 'Verify Info'
on:
  issues:
    types: [opened, edited, labeled]
    branches: [ master ]
  issue_comment:
    types: [created, edited]
    branches: [ master ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"