name: 'Verify Info'
on:
  issues:
    types: [opened]
    branches: [ master ]
  pull_request:
    types: [opened]
    branches: [ master ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          require_all:
            - '#''
            - test
          require_one:
            - codesandbox.io
            - codepen.io
            - jsbin.com
            - jsfiddle.net
