name: 'Need Info'
on:
  issues:
    types: [labeled] # 'opened' and 'edited' are also options
    branches: [master]
  issue_comment:
    types: [created] # edited' is also  an option
    branches: [master]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
